### ISSUE TITLE
Buggy aimbot / RCS

### ISSUE THREAD

**Issue by tempacc123** [sstokic-tgm/Gladiatorcheatz-Public#9]
https://youtu.be/5PO7Zn_5KDw

https://youtu.be/eSeWllgjibQ

The first vid is aimbot targetting bug.
it should moved to closest enemy but no, it moves to 2nd closest enemy.

2nd vid is a bug happens when i activates RCS and novisrecoil both features.

**Comment by sstokic-tgm** [comment]
First video: It happens due the amount of fov, if the fov is for example 6 and you target an enemy which are near(like in the video) he tries to target the other one also, lowering fov or aiming on ppl that aren't near your fov will solve the problem.

Second video: As I know, the blue square is where the server registered a hit(due to spread) so it shouldn't be a bug as long as you see impacts on the wall there where it should be :)
